#ifndef CONST_SP_1
#define CONST_SP_1

#define MAX_PIN 100000
#define MIN_PIN 0
#define PIN_CHAR_SIZE 6
#define LOGIN_SIZE 6
#define LIMIT_CHAR_SIZE 6
#define RECORD_SIZE LOGIN_SIZE + 1 + PIN_CHAR_SIZE + 1 + LIMIT_CHAR_SIZE + 1
#define PASSWORD_FILE_NAME "password.txt"
#define COMMAND_BUFF_SIZE 40
#define COMMAND_COUNT 5
#define MAX_LIMIT 999999
#define MIN_LIMIT -1
#define CONF_CODE 12345


enum RETURN_CODES{
    SL_PASS_FILE_EMPUTY = -1000,
    SL_FILE_OPEN_ERR,
    SL_READ_ERR,
    SL_LSEEK_ERR,
    LCC_ZERO_LEN,
    LCC_TOO_LONG,
    LCC_INCORRECT_CHAR,
    SPO_READ_ERR,
    SPO_TWO_ARGS,
    UPF_OPEN_FILE_ERR,
    UPF_WRITE_ERR,
    PCC_ZERO_LEN,
    PCC_INCORRECT_CHAR,
    PCC_WRONG_FORMAT,
    PCC_TOO_BIG_PIN,
    CPM_LSEEK_ERR,
    CPM_READ_ERR,
    CPM_WRONG_PASS,
    CPM_FILE_OPEN_ERR,
    M_ERR_READ_I,
    CI_READ_ERR,
    CI_BUFF_OVERFLOW,
    CI_NEW_LINE,
    CS_COM_NOT_FOUND,
    CC_LOGOUT_CODE,
    CC_UNNECESSARY_ARGS,
    HC_WRONG_ARGS,
    HC_FAILURE_CONVERSION,
    GL_FILE_OPEN_ERR,
    GL_LSEEK_ERR,
    GL_READ_ERR,
    GL_SSCANF_ERR,
    SC_WRONG_ARGS,
    SC_LSEEK_ERR,
    SC_FILE_OPEN_ERR,
    SC_READ_ERR,
    SC_WRITE_ERR,
    SC_INVALID_CODE,
};

#endif